mariadb:
  image: mariadb:10.0.23
  environment:
    MYSQL_ROOT_PASSWORD: istotallysecure
    MYSQL_DATABASE: rundeck
    MYSQL_USER: rd
    MYSQL_PASSWORD: rd

rundeck:
  image: elcolio/rdeck:test
  environment:
    MYSQL_USER: rd
    MYSQL_PASSWORD: rd
    DEFAULT_ADMIN_USER: admin
    DEFAULT_ADMIN_PASSWORD: derpN0zzle
  links:
    - mariadb:mysql
  ports:
    - 4440:4440